apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: arun-dep1
spec:
  replicas: 3
  template:
    metadata:
      name: arun-dep1
      labels:
        app: arun-dep1
    spec:
      containers:
      - image: arunvel1988/appv1
        name: appv1
---
apiVersion: v1
kind: Service
metadata:
  name: arun-dep1
spec:
  type: NodePort
  selector:
    app: arun-dep1
  ports:
  - port: 80
    targetPort: 8000
