apiVersion: v1
kind: Service
metadata:
  name: arun-service
  labels:
    app: hello-arun
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30002
    protocol: TCP
  selector:
    app: hello-arun
